# Clean and don't fail
install:
  - rm -rf public

# Build the website
script:
  - ./exec/hugo

# Deploy to GitHub pages
deploy:
  - provider: s3
    access_key_id: $S3_IAM_KEY
    secret_access_key: $S3_IAM_SECRET
    bucket: "www.effectivealtruismmelbourne.org"
    skip_cleanup: true
    local_dir: public
    s3_region: ap-southeast-2
    on:
      branch: master


